# Generated by Django 4.2 on 2026-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('answer', models.FloatField(verbose_name='Правильный ответ')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('category', models.CharField(choices=[('algebra', 'Алгебра'), ('geometry', 'Геометрия'), ('trig', 'Тригонометрия'), ('calculus', 'Математический анализ'), ('stats', 'Теория вероятностей')], default='algebra', max_length=20, verbose_name='Категория')),
                ('ege_number', models.IntegerField(default=1, help_text='Номер задачи в варианте ЕГЭ (1-18)', verbose_name='Номер в ЕГЭ')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Сложность (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача ЕГЭ',
                'verbose_name_plural': 'Задачи ЕГЭ',
                'ordering': ['ege_number', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
