# Generated by Django 4.2 on 2026-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problem_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='ege_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(),
        ),
    ]
