# Generated by Django 4.2 on 2026-01-16 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_problem_options_remove_problem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['ege_number', 'id']},
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='ege_number',
            field=models.IntegerField(choices=[(1, 'Задача 1'), (2, 'Задача 2'), (3, 'Задача 3'), (4, 'Задача 4'), (5, 'Задача 5'), (6, 'Задача 6'), (7, 'Задача 7'), (8, 'Задача 8'), (9, 'Задача 9'), (10, 'Задача 10'), (11, 'Задача 11'), (12, 'Задача 12'), (13, 'Задача 13'), (14, 'Задача 14'), (15, 'Задача 15'), (16, 'Задача 16'), (17, 'Задача 17'), (18, 'Задача 18')], default=1, verbose_name='Номер в ЕГЭ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.FloatField(verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(verbose_name='Текст задачи'),
        ),
    ]
