# Generated by Django 4.2 on 2026-01-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_problem_options_problem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='problem',
            name='ege_number',
            field=models.IntegerField(choices=[(1, 'Задача 1'), (2, 'Задача 2'), (3, 'Задача 3'), (4, 'Задача 4'), (5, 'Задача 5'), (6, 'Задача 6'), (7, 'Задача 7'), (8, 'Задача 8'), (9, 'Задача 9'), (10, 'Задача 10'), (11, 'Задача 11'), (12, 'Задача 12')], default=1, verbose_name='Номер в ЕГЭ'),
        ),
    ]
