# Generated by Django 4.2 on 2026-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_problem_created_at_alter_problem_ege_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего уникальных пользователей')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('total_correct_attempts', models.IntegerField(default=0, verbose_name='Всего правильных решений')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общая сумма баллов')),
                ('problems_by_type', models.JSONField(default=dict, help_text="Формат: {'1': {'total': 100, 'correct': 85}, ...}", verbose_name='Статистика по типам задач')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Глобальная статистика',
                'verbose_name_plural': 'Глобальная статистика',
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='Правильных решений')),
                ('total_score', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('problems_by_type', models.JSONField(default=dict, help_text="Формат: {'1': {'total': 10, 'correct': 8}, ...}", verbose_name='Статистика по типам задач')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('is_correct', models.BooleanField(verbose_name='Правильно решена')),
                ('user_answer', models.FloatField(verbose_name='Ответ пользователя')),
                ('score', models.IntegerField(default=0, verbose_name='Полученные баллы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата решения')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='Правильных решений')),
                ('total_score', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('first_solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый раз решена')),
                ('last_solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз решена')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to='home.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Статистика задачи',
                'verbose_name_plural': 'Статистика задач',
            },
        ),
    ]
