# Generated by Django 4.2 on 2026-01-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_globalstatistics_userstatistics_userproblemattempt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalStatistics',
        ),
        migrations.DeleteModel(
            name='ProblemStatistics',
        ),
    ]
